import { expect, open, sheet, test } from './app'

test('boots: lists the fixture constellation, draws the map, and throws nothing', async ({ page, errors }) => {
  await open(page)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('nebulosa')
  const satellites = sheet(page, 'Constellation')
  await expect(satellites.getByRole('button', { name: /^STRIX-1 / })).toBeVisible()
  await expect(satellites.getByRole('button', { name: /^STRIX-9 / })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Satellites · 2/ })).toBeVisible()
  await expect(page.getByText(/Elements from 2026-09-03 20:40 UTC/)).toBeVisible()
  expect(errors).toEqual([])
})

test('selecting a satellite follows it, and a drag on the map lets go', async ({ page }) => {
  await open(page)
  await sheet(page, 'Constellation')
    .getByRole('button', { name: /^STRIX-9 / })
    .click()
  await expect(page.getByRole('button', { name: /^Satellites STRIX-9/ })).toBeVisible()
  const follow = page.getByRole('button', { name: /^Follow STRIX-9/ })
  await expect(follow).toHaveAttribute('aria-pressed', 'true')
  const canvas = page.locator('.maplibregl-canvas')
  const box = (await canvas.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  for (let i = 1; i <= 10; i++) await page.mouse.move(box.x + box.width / 2 + i * 20, box.y + box.height / 2 + i * 10)
  await page.mouse.up()
  await expect(follow).toHaveAttribute('aria-pressed', 'false')
})

test('passes over the seed place are listed; showing one marks it and selects its satellite', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: /^Passes/ }).click()
  const passes = sheet(page, 'Passes')
  await expect(passes.getByText(/over Tokyo/)).toBeVisible()
  const rows = passes.getByRole('listitem')
  await expect(rows.first()).toBeVisible()
  expect(await rows.count()).toBeGreaterThan(2)
  const show = rows.first().getByRole('button').first()
  const name = (await show.textContent())!.match(/STRIX-\d/)![0]
  await show.click()
  await expect(show).toHaveAttribute('aria-current', 'true')
  await expect(page.getByRole('button', { name: new RegExp(`^Satellites ${name}`) })).toBeVisible()
  await expect(page.getByRole('button', { name: new RegExp(`^Passes ${name} \\d\\d:\\d\\d`) })).toBeVisible()
})

test('keys: 1 2 3 open the sheets, Esc peels the selection, ? shows the legend', async ({ page }) => {
  await open(page)
  await page.keyboard.press('2')
  await expect(sheet(page, 'Places')).toBeVisible()
  await expect(sheet(page, 'Places').getByRole('button', { name: /^Tokyo / })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('3')
  await expect(sheet(page, 'Passes')).toBeVisible()
  await page.keyboard.press('1')
  await sheet(page, 'Constellation')
    .getByRole('button', { name: /^STRIX-1 / })
    .click()
  await expect(page.getByRole('button', { name: /^Satellites STRIX-1/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: /^Places · none picked/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: /^Satellites · 2/ })).toBeVisible()
  await page.keyboard.press('?')
  await expect(page.getByRole('region', { name: 'Keyboard shortcuts' })).toBeVisible()
})

test('toggles: flat map, light theme and Japanese, each kept across a reload', async ({ page }) => {
  await open(page)
  const globe = page.getByRole('button', { name: 'Globe or flat map' })
  await expect(globe).toHaveAttribute('aria-pressed', 'true')
  await globe.click()
  await expect(globe).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Light or dark' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('combobox', { name: 'Language' }).selectOption('ja')
  await expect(page.getByText('StriX SAR衛星群の地上軌跡')).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja')

  await page.reload()
  await expect(page.getByText('StriX SAR衛星群の地上軌跡')).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.getByRole('button', { name: /^衛星 · 2/ })).toBeVisible()
})

test('a located place is a target at the browser position that a drag does not move', async ({ page, context }) => {
  await context.grantPermissions(['geolocation'])
  await context.setGeolocation({ latitude: 35.5, longitude: 139.6 })
  await open(page)
  await page.keyboard.press('2')
  const places = sheet(page, 'Places')
  await places.getByRole('button', { name: 'Use my location' }).click()
  const row = places.getByRole('button', { name: /^My location / })
  await expect(row).toHaveAttribute('aria-pressed', 'true')
  await expect(row).toContainText('35.50°N 139.60°E')
  await expect(places.getByRole('button', { name: 'Update my location' })).toBeVisible()
  await expect(places.getByRole('button', { name: 'Use my location' })).toHaveCount(0)

  const target = page.locator('.maplibregl-marker svg circle').first()
  await expect(target).toBeVisible()
  const box = (await target.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + 150, box.y + 150, { steps: 10 })
  await page.mouse.up()
  await expect(row).toContainText('35.50°N 139.60°E')
})
